apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.*
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/platform/security/cert-manager/values.yaml
    - repoURL: https://github.com/luzero-luvis/argo-k8s-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/luzero-luvis/argo-k8s-gitops.git
      targetRevision: main
      path: platform/security/cert-manager/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
