extends: default

rules:
  document-start: disable
  braces: disable
  colons: disable
  commas: disable
  comments:
    min-spaces-from-content: 1
  indentation: disable
  line-length:
    max: 140
    level: warning
  truthy:
    allowed-values: ["true", "false", "on"]
