image:
  name: ghcr.io/luzero-luvis/small-go-webserver:v1.0.1@sha256:a3fa35b0f92375da41e198375a0734441c86276bee214b2220298f933452045c
  pullPolicy: IfNotPresent
replicaCount: 1
containerPort: 8080
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
readinessProbe:
  enabled: true
  type: tcpSocket
  tcpSocket:
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
livenessProbe:
  enabled: true
  type: tcpSocket
  tcpSocket:
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
