resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

serviceMonitor:
  selfMonitor:
    enabled: true
    interval: 30s
  enabled: true
  defaults:
    interval: 60s
    scrapeTimeout: 15s
    module: http_2xx
  targets: []
