apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set-controller
      targetRevision: 0.14.2
      helm:
        releaseName: arc
        valueFiles:
          - $values/platform/ci-runners/arc-controller/values.yaml

    - repoURL: https://github.com/luzero-luvis/argo-k8s-gitops.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/luzero-luvis/argo-k8s-gitops.git
      targetRevision: main
      path: platform/ci-runners/arc-controller/resources

  destination:
    server: https://kubernetes.default.svc
    namespace: action-runner-controller

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
