apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: services
  sources:
    - repoURL: https://github.com/rabbitmq/cluster-operator.git
      targetRevision: v2.22.4
      path: config/installation
    - repoURL: https://github.com/luzero-luvis/argo-k8s-gitops.git
      targetRevision: main
      path: services/rabbitmq/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
