apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-jaeger
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  jaeger.yaml: |-
    apiVersion: 1
    datasources:
      - name: Jaeger
        uid: jaeger
        type: jaeger
        access: proxy
        url: http://jaeger.monitoring.svc.cluster.local:16686
        isDefault: false
        editable: false
        jsonData:
          nodeGraph:
            enabled: true
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: -1h
            spanEndTimeShift: 1h
            filterByTraceID: true
            filterBySpanID: true
            tags:
              - key: k8s.namespace.name
                value: k8s_namespace_name
