apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-badger-data
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
