apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack/application.yaml
  - loki/application.yaml
  - jaeger/application.yaml
  - otel-collector-agent/application.yaml
  - otel-collector-gateway/application.yaml
  - blackbox-exporter/application.yaml
  - dcgm-exporter/application.yaml
