apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/platform.yaml
  - projects/services.yaml
  - projects/monitoring.yaml
  - projects/workloads.yaml
  - applications/10-platform.yaml
  - applications/20-services.yaml
  - applications/30-monitoring.yaml
  - applications/40-workloads.yaml
