apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.4.4
      helm:
        releaseName: argocd
        valueFiles:
          - $values/infrastructure/controllers/argocd/values.yaml
    - repoURL: https://github.com/luzero-io/k8s-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/luzero-io/k8s-gitops.git
      targetRevision: main
      path: infrastructure/controllers/argocd/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
