apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: services
  sources:
    - repoURL: https://codecentric.github.io/helm-charts
      chart: keycloakx
      targetRevision: 7.2.2
      helm:
        releaseName: keycloak
        valueFiles:
          - $values/services/keycloak/values.yaml
    - repoURL: https://github.com/luzero-luvis/argo-k8s-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/luzero-luvis/argo-k8s-gitops.git
      targetRevision: main
      path: services/keycloak/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
