apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.19.6
      helm:
        releaseName: cilium
        valueFiles:
          - $values/platform/networking/cilium/values.yaml
    - repoURL: https://github.com/luzero-luvis/argo-k8s-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: cilium-ca
      namespace: kube-system
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: hubble-relay-client-certs
      namespace: kube-system
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: hubble-server-certs
      namespace: kube-system
      jsonPointers:
        - /data
