apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - require-resources.yaml
  - require-probes.yaml
  - require-non-root.yaml
  - require-read-only-rootfs.yaml
  - disallow-latest-tag.yaml
  - disallow-privileged.yaml
  - restrict-host-namespaces.yaml
  - verify-images.yaml
