apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-read-only-rootfs
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: read-only-root-filesystem
      match:
        any:
          - resources:
              kinds: [Pod]
      validate:
        message: Containers must use a read-only root filesystem.
        pattern:
          spec:
            containers:
              - securityContext:
                  readOnlyRootFilesystem: true
