apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: health-probes
      match:
        any:
          - resources:
              kinds: [Pod]
      validate:
        message: Containers must define readiness and liveness probes.
        pattern:
          spec:
            containers:
              - livenessProbe: {}
                readinessProbe: {}
