apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 3

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak

  storage:
    storageClass: longhorn
    size: 10Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

  monitoring:
    enablePodMonitor: true

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
